import type {
  Assessment,
  AuditEvent,
  AuthorisedAccount,
  ChallengeReview,
  Claim,
  EvidenceItem,
  HumanDecision,
  Proposition,
  RevisionRecord,
} from "./types";

export const DEMO_NOW = "15 July 2026 · 10:30 BST";

export const initialClaim: Claim = {
  id: "RB-CLM-001",
  wording: "Signal crayfish caused the reported decline in fish in the River Barle.",
  location: "Upper River Barle, Exmoor",
  period: "Reported recent change; precise baseline not supplied",
  intendedUse: "Public educational statement",
  consequence: "medium",
};

export const initialEvidence: EvidenceItem[] = [
  {
    id: "RB-E01",
    title: "Submitted report of reduced fish visibility",
    organisation: "Demonstrator claimant",
    date: "Date not independently verified",
    kind: "reported-observation",
    sourceType: "submitted testimony",
    summary: "A local concern reports fewer fish being seen in the assessed reach.",
    geographicScope: "Claimed River Barle reach; exact coordinates withheld",
    temporalScope: "Recent period; no comparable series supplied",
    supports: "A decline has been reported.",
    doesNotSupport: "A measured population trend or the cause of any decline.",
    limitations: "Testimony only; no standardised sampling, baseline or effort record.",
    rights: "Demonstrator summary; no personal data or original correspondence published.",
    admissionStatus: "submitted",
  },
  {
    id: "RB-E02",
    title: "River Barle Crayfish Project: local pressure description",
    organisation: "Exmoor National Park Authority",
    date: "Project begun 2015; page accessed July 2026",
    url: "https://www.exmoor-nationalpark.gov.uk/nature-and-landscape/nature-recovery/ennis-project/about-the-ennis-project/river-barle-crayfish-project",
    kind: "local-observation",
    sourceType: "public authority",
    summary: "The project records a River Barle signal-crayfish population and identifies burrowing, erosion and siltation as recognised negative impacts.",
    geographicScope: "Five-mile River Barle stretch; not the precise claimed micro-reach",
    temporalScope: "Population found in 2014; project from 2015",
    supports: "A locally relevant physical pressure pathway warrants assessment.",
    doesNotSupport: "That crayfish caused all local bank disturbance or any fish decline.",
    limitations: "Project description, not a comparative causal study of fish abundance.",
    rights: "Public webpage; linked and paraphrased for public educational use.",
    admissionStatus: "submitted",
  },
  {
    id: "RB-E03",
    title: "Signal crayfish recorded in the River Barle",
    organisation: "Exmoor National Park Authority",
    date: "Population found in 2014",
    url: "https://www.exmoor-nationalpark.gov.uk/nature-and-landscape/nature-recovery/ennis-project/about-the-ennis-project/river-barle-crayfish-project",
    kind: "presence",
    sourceType: "public authority",
    summary: "A signal-crayfish population was found along a five-mile stretch of the River Barle.",
    geographicScope: "River Barle project stretch",
    temporalScope: "2014 onward",
    supports: "Signal crayfish are present in a relevant part of the River Barle.",
    doesNotSupport: "Current density, presence at every location, material local impact or fish causation.",
    limitations: "Presence is not a quantified exposure or causal estimate.",
    rights: "Public webpage; linked and paraphrased.",
    admissionStatus: "submitted",
  },
  {
    id: "RB-E04",
    title: "Guidance on habitat for white-clawed crayfish",
    organisation: "Environment Agency / English Nature",
    date: "2003",
    url: "https://assets.publishing.service.gov.uk/media/5a7cb8d9ed915d6822362247/sw1-067-tr-e-e.pdf",
    kind: "mechanism",
    sourceType: "agency guidance",
    summary: "Agency guidance reports that signal crayfish burrow more deeply and extensively than white-clawed crayfish.",
    geographicScope: "General mechanism; not River Barle-specific",
    temporalScope: "Published 2003; mechanism remains relevant but dated",
    supports: "Burrowing and associated bank pressure are biologically plausible mechanisms.",
    doesNotSupport: "That the mechanism operated materially in the assessed reach and period.",
    limitations: "General guidance cannot establish site-specific causation.",
    rights: "Government-hosted technical report; linked and briefly paraphrased.",
    admissionStatus: "submitted",
  },
  {
    id: "RB-E05",
    title: "Environment Agency response: fish evidence and multiple pressures",
    organisation: "Environment Agency response published by Mid Devon District Council",
    date: "March 2024",
    url: "https://democracy.middevon.gov.uk/documents/s30412/Responses%2Bto%2BQuestions%2Basked%2Bof%2Bthe%2BEnvironment%2BAgency.pdf",
    kind: "alternative",
    sourceType: "public authority",
    summary: "The response cites 51 salmon in a 2023 Simonsbath survey and identifies climate, passage barriers, marine fisheries, runoff, discharges and water resources as relevant pressures.",
    geographicScope: "Simonsbath and wider Exe catchment; not a complete Barle trend analysis",
    temporalScope: "Survey example from 2023",
    supports: "Contrary evidence and plausible alternative pressures must be considered.",
    doesNotSupport: "That no decline exists anywhere, or that any alternative alone caused change.",
    limitations: "A single survey count is not a comparable time series; wider-catchment statements have spatial limits.",
    rights: "Public committee document; linked and paraphrased.",
    admissionStatus: "submitted",
  },
  {
    id: "RB-E06",
    title: "Funding record for invasive-crayfish control",
    organisation: "Exmoor National Park Authority — Farming in Protected Landscapes",
    date: "2022–2024 programme record",
    url: "https://www.exmoor-nationalpark.gov.uk/__data/assets/pdf_file/0017/7406/Transparency-of-Funding-yr2.pdf",
    kind: "institutional",
    sourceType: "public authority",
    summary: "The record confirms a £9,450 grant within a £28,360 project for control planning, traps, sightings and analysis on the Barle and Exe.",
    geographicScope: "Barle and Exe programme area",
    temporalScope: "11 May 2022 to 31 March 2024",
    supports: "Expenditure, intended activity and delivery responsibility existed.",
    doesNotSupport: "Ecological recovery, successful control, breach of duty or causation of harm.",
    limitations: "Transparency record describes funding and purpose, not measured ecological outcome.",
    rights: "Public transparency document; linked and paraphrased.",
    admissionStatus: "submitted",
  },
];

export const updateEvidence: EvidenceItem = {
  id: "RB-E07",
  title: "Later reach-specific professional bank survey",
  organisation: "Demonstrator professional-survey packet",
  date: "Later evidence scenario",
  kind: "local-observation",
  sourceType: "submitted testimony",
  summary: "A professional survey records substantial signal-crayfish burrowing and associated bank disturbance within the exact assessed reach.",
  geographicScope: "Exact assessed reach",
  temporalScope: "Later evidence point",
  supports: "Signal crayfish contribute to local bank disturbance.",
  doesNotSupport: "That signal crayfish caused the reported fish decline.",
  limitations: "Demonstrator update scenario; underlying professional report must be supplied before real-world use.",
  rights: "Restricted demonstrator summary; not for external factual reliance.",
  admissionStatus: "submitted",
};

export const propositions: Proposition[] = [
  { id: "RB-C01", text: "Fish have declined in the assessed reach.", type: "observation", evidenceIds: ["RB-E01", "RB-E05"], status: "amber", finding: "Reported, not established as a measured trend.", missing: "Comparable monitoring with method and effort." },
  { id: "RB-C02", text: "Signal crayfish are present in a relevant stretch of the River Barle.", type: "presence", evidenceIds: ["RB-E03"], status: "green", finding: "Supported for the project stretch.", missing: "Precise current density and micro-reach confirmation." },
  { id: "RB-C03", text: "Signal-crayfish burrowing can contribute to erosion and siltation.", type: "mechanism", evidenceIds: ["RB-E02", "RB-E04"], status: "green", finding: "General mechanism supported.", missing: "Material operation at the claimed place and time." },
  { id: "RB-C04", text: "Signal crayfish contributed to local bank disturbance.", type: "local-inference", evidenceIds: ["RB-E02", "RB-E03", "RB-E04"], status: "amber", finding: "Plausible, but reach-specific material contribution is not yet demonstrated.", missing: "Dated reach-specific professional observation." },
  { id: "RB-C05", text: "Signal crayfish caused the reported fish decline.", type: "causal-inference", evidenceIds: ["RB-E01", "RB-E02", "RB-E03", "RB-E04", "RB-E05"], status: "red", finding: "Not established; the inference crosses several unsupported steps.", missing: "Comparable fish trend, exposure, causal analysis and evaluation of alternatives." },
  { id: "RB-C06", text: "A named body is responsible for ecological loss.", type: "responsibility", evidenceIds: ["RB-E06"], status: "red", finding: "Not established; funding and delivery records do not prove harm, duty failure or liability.", missing: "Authoritative duty, act or omission, failure and proportionate causal evidence." },
  { id: "RB-C07", text: "Monitoring and decision functions can be identified despite unresolved causation.", type: "responsibility", evidenceIds: ["RB-E05", "RB-E06"], status: "amber", finding: "Candidate functions can be mapped cautiously.", missing: "Formal role confirmation for any real-world assignment." },
];

export const fallbackAssessment: Assessment = {
  id: "RB-ASMT-001",
  version: "0.1",
  model: "GPT-5.6",
  generatedAt: DEMO_NOW,
  overallRoute: "red",
  preliminaryConclusion: "The supplied evidence supports a plausible pressure pathway involving signal crayfish, bank disturbance and possible habitat effects, but it does not establish that signal crayfish caused the reported decline in fish.",
  safeConclusion: "Signal crayfish are present in a relevant River Barle stretch and provide a plausible contributor to bank pressure. Local material contribution and causation of the reported fish decline remain unresolved.",
  causalGap: "Presence plus a general mechanism does not establish local material contribution; local contribution plus a reported decline does not establish causation.",
  alternatives: ["Climate change and temperature", "Flow and water-resource pressures", "Barriers to fish passage", "Marine fisheries", "Agricultural and diffuse runoff", "Water-company and private discharges"],
  unresolved: ["No comparable fish-abundance baseline", "No reach-specific exposure estimate", "No analysis separating competing pressures", "No demonstrated ecological outcome from funded control activity"],
  propositionIds: propositions.map((item) => item.id),
  modelMode: "verified-demonstrator-packet",
};

export const challengeReview: ChallengeReview = {
  id: "RB-CHAL-001",
  assessmentId: fallbackAssessment.id,
  createdAt: DEMO_NOW,
  objections: [
    "The submitted wording converts a reported observation into a measured trend.",
    "It moves from catchment presence and general mechanism to reach-specific contribution without sufficient local evidence.",
    "It attributes fish decline without comparing plausible alternative pressures.",
  ],
  missingEvidence: ["Comparable fish surveys", "Reach-specific bank and burrow survey", "Temporal linkage", "Multi-pressure causal assessment"],
  alternativeExplanations: fallbackAssessment.alternatives,
  stopTriggered: true,
  recommendation: "revise",
  mayAuthorise: false,
};

export const defaultDecision: HumanDecision = {
  id: "RB-DEC-001",
  action: "revise-and-approve",
  reviewer: "Roger Watts",
  role: "Creator and designated demonstrator reviewer",
  decidedAt: DEMO_NOW,
  refusedWording: initialClaim.wording,
  approvedWording: fallbackAssessment.safeConclusion,
  permittedUse: "Public education only",
  consequence: "Medium — public statement; no allegation, regulatory or legal use",
  unresolvedQuestions: fallbackAssessment.unresolved,
  reviewTrigger: "Reach-specific professional survey or comparable fish-monitoring series",
};

export const accountV1: AuthorisedAccount = {
  id: "RB-ACC-001",
  version: "1.0",
  createdAt: DEMO_NOW,
  submittedClaim: initialClaim.wording,
  submittedClaimDecision: "Refused for public use",
  authorisedConclusion: defaultDecision.approvedWording,
  permittedUse: defaultDecision.permittedUse,
  evidenceIds: initialEvidence.map((item) => item.id),
  assessmentId: fallbackAssessment.id,
  challengeReviewId: challengeReview.id,
  decisionId: defaultDecision.id,
  ecologicalAccount: [
    "Expenditure confirmed.",
    "Activity confirmed.",
    "Output partially described.",
    "Ecological outcome not demonstrated.",
    "Recovery unverified — no ecological gain recognised in the account.",
  ],
  responsibilities: [
    { category: "Causal responsibility", finding: "Unresolved", status: "unresolved" },
    { category: "Relevant statutory functions", finding: "Environment Agency functions identified provisionally from public material", status: "candidate" },
    { category: "Delivery responsibility", finding: "Funded intervention and delivery organisation identified", status: "identified" },
    { category: "Monitoring responsibility", finding: "Candidate owner requires formal confirmation", status: "candidate" },
    { category: "Decision responsibility", finding: "Designated human reviewer controls this educational account", status: "identified" },
    { category: "Corrective responsibility", finding: "Not assignable without established duty and failure", status: "unresolved" },
    { category: "Legal liability", finding: "Outside automated assessment", status: "outside-scope" },
  ],
  packet: {
    accountVersion: "1.0",
    authorisedConclusion: defaultDecision.approvedWording,
    approvedUncertainties: fallbackAssessment.unresolved,
    prohibitedClaims: [initialClaim.wording, "A named organisation caused or failed to prevent the reported harm."],
    permittedUse: defaultDecision.permittedUse,
    disclosureConstraints: ["Do not imply ecological recovery from expenditure or activity", "Do not assign legal or causal responsibility", "Preserve uncertainty about fish decline"],
  },
};

export const voiceV1 = "The River Barle account asks us to look carefully before we speak confidently. Signal crayfish are present, and their burrowing provides a credible reason to investigate local bank pressure. But the admitted evidence does not tell us that they caused the reported change in fish. The honest public account is therefore unfinished: recovery has not been demonstrated, causation remains open, and better reach-specific monitoring is the responsible next step.";

export const accountV11: AuthorisedAccount = {
  ...accountV1,
  id: "RB-ACC-002",
  version: "1.1",
  createdAt: "15 July 2026 · 11:10 BST",
  authorisedConclusion: "New reach-specific evidence supports signal crayfish as a contributor to local bank disturbance. It does not establish that they caused the reported decline in fish.",
  evidenceIds: [...accountV1.evidenceIds, updateEvidence.id],
  supersedes: accountV1.id,
  packet: {
    ...accountV1.packet,
    accountVersion: "1.1",
    authorisedConclusion: "New reach-specific evidence supports signal crayfish as a contributor to local bank disturbance. It does not establish that they caused the reported decline in fish.",
  },
};

export const revisionV11: RevisionRecord = {
  id: "RB-REV-001",
  fromVersion: "1.0",
  toVersion: "1.1",
  createdAt: accountV11.createdAt,
  newEvidenceId: updateEvidence.id,
  changed: ["Confidence in local bank contribution increased", "Monitoring and management recommendation narrowed to the exact reach"],
  unchanged: ["Fish-decline causation remains unresolved", "Original refused wording remains refused", "Permitted use remains public education only"],
  priorAccountPreserved: true,
};

export const initialAudit: AuditEvent[] = [
  { id: "AUD-001", at: DEMO_NOW, actor: "Roger Watts", action: "submitted", object: initialClaim.id, detail: "Claim entered for public educational use" },
];
